package lox;

enum TokenType {
    // single character tokens
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, SEMICOLON, QUESTION_MARK, COLON,

    // one or two (or three) character tokens
    AMPERSAND, AMPERSAND_EQUAL,
    BANG, BANG_EQUAL,
    CARET, CARET_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    GREATER_GREATER, GREATER_GREATER_EQUAL,
    LESS, LESS_EQUAL,
    LESS_LESS, LESS_LESS_EQUAL,
    MINUS, MINUS_EQUAL,
    PERCENT, PERCENT_EQUAL,
    PIPE, PIPE_EQUAL,
    PLUS, PLUS_EQUAL,
    SLASH, SLASH_EQUAL,
    STAR, STAR_EQUAL,
    TILDE, TILDE_EQUAL,

    // literals
    IDENTIFIER, STRING, NUMBER,

    // keywords
    AND, BREAK, CLASS, CONST, DO, ELSE, END, FALSE, FUN,
    FOR, IF, LET, NIL, OR, RETURN, SUPER, THIS, TRUE, WHILE,

    EOF
}
